### ISSUE TITLE
KVM in Ansible contrib?

### ISSUE THREAD

**Issue by devekko** [swayf/proxmoxer#11]
hi 

does proxmoxer currently handle KVM vms via the Ansible contrib module?

https://github.com/ansible/ansible-modules-extras/issues/1004

https://github.com/swayf/proxmoxer/issues/7#issuecomment-124170426

**Comment by swayf** [comment]
Proxmoxer can handle KVM, but it does not use Ansible for that :). If ansible contrib module is written in the right way, it should work with both KVM and OpenVZ. From the first shot code review, right now, it does use KVM part of the interface.
