### ISSUE TITLE
create fails with 501 Not Implemented

### ISSUE THREAD

**Issue by chicks-net** [swayf/proxmoxer#23]
I've written a script to create VM's in proxmox:

```
$ cat picknode 
#!/usr/bin/env python

from proxmoxer import ProxmoxAPI
#from hurry.filesize import size
import getpass
import pprint
import re
import operator

pp = pprint.PrettyPrinter(indent=5)

apipass = getpass.getpass()

proxmox = ProxmoxAPI('proxmox1-oak.telmate.cc', user='chicks@TELMATE.CC',
                     password=apipass, verify_ssl=False)

def discover_nodes():
    picker = {
            'staging': {}, 
            'prod': {}, 
            'db': {}, 
    }

    for node in proxmox.nodes.get():
        node_name = node['node']
        #print node_name + ":"
        mem_perc = 100*node['mem']/node['maxmem']
        #print "mem={0:.3f}%".format(mem_perc)
        
        if re.match(".*staging",node_name):
            picker['staging'][node_name] = mem_perc
        elif re.match(r".*db\d+-.*",node_name):
            picker['db'][node_name] = mem_perc
        else:
            picker['prod'][node_name] = mem_perc

    return picker;

#pp.pprint(picker)

def pick(env):
    picker = discover_nodes()

    if not env in picker:
        raise LookupError(env + " is not a valid environment")

    sorted_nodes = sorted(picker[env].items(), key=operator.itemgetter(1))
    #pp.pprint(sorted_nodes)

    return sorted_nodes[0][0];

def nextvmid():
    netmax = 0
    othermax = 0
    for vm in proxmox.cluster.resources.get(type='vm'):
        #pp.pprint(vm)
        vmid = vm['vmid']
        if vmid > 3300:
            # netops
            if vmid > netmax:
                netmax = vmid
        else:
            # not netops
            if vmid > othermax:
                othermax = vmid

    # handle overflow of other
    if othermax < 3300-1:
        return othermax+1
    else:
        return netmax+1

vmid = nextvmid()
print "vmid={0:d}".format(vmid)
picked = pick('prod')
print "picked {0}".format(picked)

node = proxmox.node(picked)
print type(node)
#pp.pprint(node)

node.openvz.create(vmid=vmid,
                   ostemplate='',
                   hostname='chicks-test0',
                   storage='local',
                   memory=512,
                   swap=512,
                   cpus=1,
                   disk=4,
                   password='PLACEHOLDER',
                   ip_address='10.33.8.116')
```

I'm really trying to create `qemu` VM's but I figured I would try to follow the posted example closer.  Either way I get:

```
$ ./picknode 
Password: 
vmid=242
picked proxmox7-oak
<class 'proxmoxer.core.ProxmoxResource'>
Traceback (most recent call last):
  File "./picknode", line 91, in <module>
    ip_address='10.33.8.116')
  File "/home/chicks/Documents/proxmox-api/venv.proxmox/local/lib/python2.7/site-packages/proxmoxer/core.py", line 96, in create
    return self.post(*args, **data)
  File "/home/chicks/Documents/proxmox-api/venv.proxmox/local/lib/python2.7/site-packages/proxmoxer/core.py", line 87, in post
    return self(args)._request("POST", data=data)
  File "/home/chicks/Documents/proxmox-api/venv.proxmox/local/lib/python2.7/site-packages/proxmoxer/core.py", line 79, in _request
    raise ResourceException("{0} {1}".format(resp.status_code, httplib.responses[resp.status_code]))
proxmoxer.core.ResourceException: 501 Not Implemented
```

I'm running PVE manager version `pve-manager/3.4-13/4c74557`.

**Comment by chicks-net** [comment]
# bug update

Upon further research I have noticed a number of issues with how the API is trying to create VM's.  The URL's generated by the API differ from the web client look like `/api2/extjs/nodes/proxmox-synergy1-bri/qemu ` while the python generates `/api2/json/node/proxmox7-oak/openvz`.

And the parameters are quite different looking:

	## URLEncoded form from web UI request
	vmid:    131
	name:    members-app2-bri.telmate.cc
	ostype:  l26
	ide2:    local:iso/ubuntu-14.04.2-server-amd64.iso,media=cdrom
	ide0:    ProxmoxSynergy1ZFSoiSCSI:40
	sockets: 1
	cores:   2
	numa:    0
	cpu:     host
	memory:  4096
	net0:    e1000,bridge=vmbr0,tag=10

	## URLEncoded form from python
	disk:       4
	vmid:       273
	hostname:   chicks-test0
	storage:    local
	cpus:       1
	ostemplate:
	swap:       512
	memory:     512
	password:   PLACEHOLDER
	ip_address: 10.33.8.116
	
so I alter the code to be closer what the web UI sends:

     node.qemu.create(vmid=vmid,
                   hostname='chicks-test0.telmate.cc',
                   cpu='host',
                   net0='e1000,bridge=vmbr0,tag=10',
                   ide0='Proxmox7ZFSoiSCSI:40', # may need vmid embedded?
                   ide2='local:iso/ubuntu-14.04.2-server-amd64.iso,media=cdrom',
                   ostype='l26',
                   memory=512,
                   sockets=1,
                   cores=2,
                   numa=0)

which leads to a URL of `/api2/json/node/proxmox7-oak/qemu` and paramaters that look right now:

    ## URLEncoded form 
    hostname: chicks-test0.telmate.cc
    vmid:     273
    cpu:      host
    numa:     0
    memory:   512
    ostype:   l26
    cores:    2
    ide0:     Proxmox7ZFSoiSCSI:40
    sockets:  1
    ide2:     local:iso/ubuntu-14.04.2-server-amd64.iso,media=cdrom
    net0:     e1000,bridge=vmbr0,tag=10

still returns 501 so I'm left guessing the URL is the issue.  I don't see an easy way to fix this.

**Comment by chicks-net** [comment]
I gave up on this API and got it working with [Perl](https://github.com/mrproper/proxmox-ve-api-perl). The availability of a low-level API in the Perl wrapper made it easy to do what we wanted.

**Comment by kryogenic** [comment]
Generally, with the Proxmox API, 501 Not Implemented means your URL is wrong. Since the python code gets translated directly to the URL (i.e. `proxmox.nodes('my_node').openvz.create(...)` => `POST /api2/json/nodes/my_node/openvz`) this generally means you made a typo when calling the API in python.

**Comment by chicks-net** [comment]
Thanks.
