### ISSUE TITLE
PVE API docs link in description is broken

### ISSUE THREAD

**Issue by JedMeister** [swayf/proxmoxer#31]
The link to the PVE API docs (contained in the GH description; and on [Pypi](https://pypi.python.org/pypi/proxmoxer)) is no longer valid. I.e.:

>python wrapper for Proxmox API v2 (http://pve.proxmox.com/pve2-api-doc/)

General PVE API info is on their wiki:
https://pve.proxmox.com/wiki/Proxmox_VE_API

And the full PVE API docs now appear to be here:
https://pve.proxmox.com/pve-docs/api-viewer/index.html

**Comment by BrianSidebotham** [comment]
+1
