### ISSUE TITLE
Return response content in case of non 400 response

### ISSUE THREAD

**Issue by chris968** [swayf/proxmoxer#33]
Here is a way to retrieve the content of the response in case of non 400 response from the API ?
For example when you create a new Qemu virtual machine and the storage volume do not exist the API return a code 500 with a message like "volume do not exist"

**Comment by EmmanuelKasper** [comment]
this has been adressed in https://github.com/swayf/proxmoxer/pull/36

**Comment by swayf** [comment]
done
