### ISSUE TITLE
Please add missing files to the released tarball

### ISSUE THREAD

**Issue by valholl** [swayf/proxmoxer#39]
Hello.

I've noticed that the tarball released on pypi (https://pypi.python.org/pypi/proxmoxer) is missing the LICENSE file; besides being useful to check the actual terms of the license, this incidentally makes that tarball non redistributable, as it's missing the notice required by the license itself.

I think it would also be nice to include the tests directory in the tarball: while not everybody needs them, I often find them useful as documentation and to check that a module has been correctly installed (and they would make my life easier when packaging proxmoxer for debian).

Thanks in advance.

**Comment by swayf** [comment]
Thank you for the INFO =) done
