### ISSUE TITLE
Handling ssh-public-key

### ISSUE THREAD

**Issue by stappersg** [swayf/proxmoxer#43]
Extending the example of creating an LXC container with ``ssh-public-keys`` yields the error
`SyntaxError: keyword can't be an expression`

I have a patch prepared for documenting how to handle `ssh-public-keys`.

In this issue I can tell more then in a commit message of the upcoming pull request.

First time I encounter the `SyntaxError: keyword can't be an expression`
I wrongly thought it was Python detecting an arithmetic operation.
So I tried to solve it outside the Python code, request rewrites with `mitmproxy` and even modifying the proxmox API code.

With my patch on `README.rst` I hope that others can easy use proxmoxer and SSH keys in the created container.

**Comment by swayf** [comment]
Thank you for PR :) it is merged, I will publish the new version this weekend
