### ISSUE TITLE
Failing test: tests.https_tests.test_https_connection

### ISSUE THREAD

**Issue by valholl** [swayf/proxmoxer#48]
Running the tests (from the relased tarball proxmoxer-1.0.2.tar.gz) with `nosetests3 tests.https_tests tests.paramiko_tests` I get the following failure (nosetests with python2 gives a similar, but not identical error):

```
======================================================================
ERROR: tests.https_tests.test_https_connection
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/valhalla/tmp/proxmoxer/proxmoxer-1.0.2/tests/https_tests.py", line 16, in test_https_connection
    call = req_session.return_value.request.call_args[1]
TypeError: 'NoneType' object is not subscriptable
```

Am I correct in understanding that this is because the test suite is expecting a proxmox server at `proxmox`, which other people are probably not going to have.

Should it be mentioned somewhere in the docs, (and/or in a comment in the code)?

**Comment by swayf** [comment]
hm.. The tests does not expecting server at all :) The tests should work without any servers. You can see the results of the test in travis, for example.
