### ISSUE TITLE
ImportError: cannot import name ProxmoxAPI

### ISSUE THREAD

**Issue by mleone87** [swayf/proxmoxer#50]
I've this error when I try to use proxmoxer

Tried on Debian 9 and Ubuntu 16.04

Package dependecies are installed
```

root@localhost:~# cat proxmoxer.py
from proxmoxer import ProxmoxAPI
proxmox = ProxmoxAPI('_my_ip_', user='root@pam',
                     password='***', verify_ssl=False)
```

```
Traceback (most recent call last):
   File "proxmoxer.py", line 1, in <module>
     from proxmoxer import ProxmoxAPI
   File "/root/proxmoxer.py", line 1, in <module>
     from proxmoxer import ProxmoxAPI
ImportError: cannot import name ProxmoxAPI
```

Any ideas?

**Comment by WesleyThurner** [comment]
Can you please post a 'pip -list'?  Also what python version are you using?

I just installed it in a new pipenv with no issues. Im using Python 3.6 and used the below:

pip install proxmoxer requests paramiko

**Comment by swayf** [comment]
There is no additional info. I close this for now. Dont hesistate reopen it, if you still has the problem.
