### ISSUE TITLE
Documentation on arguments and options

### ISSUE THREAD

**Issue by BarbzYHOOL** [swayf/proxmoxer#51]
Hello

I would like to know where I can find the list of arguments, notably for "netif" like in:

        net0='name=eth0,bridge=vmbr0,ip=192.168.22.1/20,gw=192.168.16.1')

**Comment by swbsf** [comment]
Hey,
Let say Proxmox documentation is not always clear or easy to find. Concerning the API you can mix these 2 links for some information : 

https://pve.proxmox.com/pve-docs/api-viewer/index.html
https://pve.proxmox.com/pve-docs/pve-admin-guide.html

**Comment by BarbzYHOOL** [comment]
this is horrible :'( I will bookmark it but there are few chances I'll find anything quickly in these (if ever needed)

I had to find the var on google and would've never find it otherwise

Isn't the quote I made related to proxmoxer first before proxmox though?

**Comment by swbsf** [comment]
Actually no, this is all proxmox, proxmoxer is just pushing the arguments to proxmox.
Just realized that maybe the best place for a full list of arguments is proxmox itself.
From the server's command line just look at the manpage for `pct` (LXC container) and `qm`.
Good luck!

**Comment by stappersg** [comment]
API viewer is also available on each Proxmox VE server.

Cheers
Geert Stappers
Who would like to see this issue be closed.
