### ISSUE TITLE
Allow port specification in hostname

### ISSUE THREAD

**Issue by pvanagtmaal** [swayf/proxmoxer#53]
Right now, specifying a hostname with a port causes the API URL to have both the default `port` parameter and the one specified in the hostname. A module directly affected by this is the Ansible [proxmox_kvm module](https://docs.ansible.com/ansible/latest/modules/proxmox_kvm_module.html) which currently doesn't allow specifying a port. 

I know the issue actually is with the Ansible module, but you might as well just add this here since it is a small change makes it more versatile.

**Comment by gerhard-tinned** [comment]
I also need a configurable port. I came across this issue by using Ansible proxmox_kvm as well. 

In any way, It would be great if the port could be passed to it as well.

**Comment by swayf** [comment]
Thank you for you RP. It is merged now. I will publish the new version this weekend.
