### ISSUE TITLE
KeyError: 599

### ISSUE THREAD

**Issue by Big4SMK** [swayf/proxmoxer#58]
Proxmox can return HTTP status 599, which is not defined in any RFC, but fairly commonly used. Proxmoxer doesn't handle this correctly as it has no safeguards around looking up the httpstatus code in http.client. Code can be found in core.py lines 77-79
```python
if resp.status_code >= 400:
            raise ResourceException("{0} {1}: {2}".format(resp.status_code, httplib.responses[resp.status_code],
                                                          resp.content))
```

suggestion would be to check if `resp.status_code` is in httplib.responses, and if not, throw a different error

**Comment by Big4SMK** [comment]
Looks like the errors are coming from AnyEvent, see https://metacpan.org/pod/AnyEvent::HTTP.

**Comment by jrjsmrtn** [comment]
I have a similar problem with a 596 HTTP status code.

**Comment by lukasmrtvy** [comment]
I have same problem with uploading vztmpl template with proxmox_template ansible module

```  
File "/home/user/.local/lib/python2.7/site-packages/proxmoxer/core.py", line 84, in get
    return self(args)._request("GET", params=params)
  File "/home/user/.local/lib/python2.7/site-packages/proxmoxer/core.py", line 78, in _request
    raise ResourceException("{0} {1}: {2}".format(resp.status_code, httplib.responses[resp.status_code],
```

```
uploading of template alpine-3.6-default_20180913_amd64.tar.xz failed with exception: 596
```

**Comment by ShadowScorpion** [comment]
Any updates regarding this issue? Someone have found workaround of this?

**Comment by jrjsmrtn** [comment]
@ShadowScorpion: as @Big4SMK discovered, the problem is caused by HTTP non-standard response codes returned by the AnyEvent::HTTP library on the Proxmox server. Those are not handled by proxmoxer.

I submitted a patch in PR #69.

**Comment by ShadowScorpion** [comment]
Got it! thanks

**Comment by Big4SMK** [comment]
This has been fixed in the new repo: https://github.com/proxmoxer/proxmoxer/commit/4b2f7167e1fd632143d75ea2494cb5653562cf68
