### ISSUE TITLE
proxmox.nodes(node['node']).openvz.get() gets 0 VMs on Proxmox 3.3-5

### ISSUE THREAD

**Issue by wdoekes** [swayf/proxmoxer#7]
Hi there,

when writing proxtop [1] I noticed that your example -- from the README.rst -- to get all VMs did not work:

    print("your example")
    for node in proxmox.nodes.get():
        for vm in proxmox.nodes(node['node']).openvz.get():
            print("{0}. {1} => {2}" .format(vm['vmid'], vm['name'], vm['status']))
        print("--")

Yields:

    your example
    --
    --
    --

Instead, I used this:

    print("my example")
    for vm in proxmox.cluster.resources.get(type='vm'):
        print("{0}. {1} => {2}" .format(vm['vmid'], vm['name'], vm['status']))

Which yields:

    127. private-herman => running
    276. acme-bugs-bunny => stopped
    443. acme-elmer-fudd => running

Thanks for the API B.T.W.! When comparing it, I favored it over the pyproxmox competition [2].

[1] https://github.com/ossobv/proxtop
[2] http://wjd.nu/notes/2015#proxmox-api-python-module

**Comment by swayf** [comment]
Thank you for the info. I will fix it in readme :)

**Comment by swayf** [comment]
Strange.. In my case works both examples... Do you have openVZ containers? or only KVM machines?

**Comment by wdoekes** [comment]
Oh, haha.

I wasn't aware of any distinction. I bet we only use KVM. Probably I would've found those VMs by checking in /qemu instead of /openvz.

Heh, that's what I get for copying examples instead of properly reading. Sorry! :)

**Comment by niccolox** [comment]
sorry, I don't understand this issue

does Proxmoxer support KVM AND openvz or ONLY openvz?

the examples on the README only have openvz

also the Ansible module seems to only imply openvz only

**Comment by swayf** [comment]
no.. you can do the same also for qemu. For example: 
```python
for node in proxmox.nodes.get():
    for vm in proxmox.nodes(node['node']).qemu.get():
        print "{0}. {1} => {2}" .format(vm['vmid'], vm['name'], vm['status'])
```

or you can get both:
```python
for vm in proxmox.cluster.resources.get(type='vm'):
    print("{0}. {1} => {2}" .format(vm['vmid'], vm['name'], vm['status']))
```

**Comment by niccolox** [comment]
Awesome

Does the Ansible Extras module do kvm also?
