### ISSUE TITLE
PVE 6 Beta: 'authorization on proxmox cluster failed with exception: invalid literal for float(): 6-0.1'

### ISSUE THREAD

**Issue by morph027** [swayf/proxmoxer#79]
Source: https://forum.proxmox.com/threads/proxmox-ve-6-0-beta-released.55670/page-3#post-257027

[Reason](https://forum.proxmox.com/threads/proxmox-ve-6-0-beta-released.55670/page-3#post-257034):

> Yes, the "GET /nodes/{nodename}/version" call changed it's return format a bit, from PVE 5:

```
# pvesh get /nodes/dev5/version --output-format=json-pretty
{
   "release" : "11",
   "repoid" : "6df3d8d0",
   "version" : "5.4"
}
```

```
pvesh get /nodes/dev6/version --output-format=json-pretty
{
   "release" : "6.0",
   "repoid" : "c148050a",
   "version" : "6.0-1"
}
```

> In short, the relase is now the main Proxmox VE relase (6.0 or 6.1 for example) repoid stayed the same and version is the full current manager version, (i.e., what the concatenation of "release" and "version" from the old 5.X call)
>
> see https://git.proxmox.com/?p=pve-manager.git;a=commitdiff;h=b597d23d354665ddea247c3ad54ece1b84921768 for full details.

**Comment by GreatWhiteMuffloN** [comment]
Yep, also having this issue.

**Comment by morph027** [comment]
Just tested:

```
>>> proxmox = ProxmoxAPI('proxmox.example.com', user='root@pam', password='super-secret-password', verify_ssl=False)
>>> for node in proxmox.nodes.get():
...     for vm in proxmox.nodes(node['node']).lxc.get():
...         print("{}: {}".format(vm['vmid'], vm['status']))
... 
111: running
121: running
106: stopped
100: running
101: running
113: running
117: running
114: stopped
118: running
124: running
102: running
125: running
108: stopped
122: running
```

**Comment by morph027** [comment]
I'm unable to reproduce right now, will ask for further details in proxmox forums.

**Comment by morph027** [comment]
Now i'm encountering this issue using the proxmox_kvm ansible module, will try to dig in.

**Comment by morph027** [comment]
Found it, quick fix is to change in `proxmox_kvm.yml`

```python
        PVE_MAJOR_VERSION = 3 if float(proxmox.version.get()['version']) < 4.0 else 4
```

to

```python
        pve_version = re.sub(r'-\d$', '', proxmox.version.get()['version'])
        PVE_MAJOR_VERSION = 3 if float(pve_version) < 4.0 else int(pve_version.split('.')[0])
```

I'll add an PR to the upstream ansible module.

**Comment by GreatWhiteMuffloN** [comment]
I had to change proxmox.py as well, containers didn't work, just copy pasted your code into proxmox.py instead of proxmox_kvm.py and copy/pasted the global results.

Now it's complaining about my indents, as it should :)

**Comment by GreatWhiteMuffloN** [comment]
If you got your proxmoxer package from Ubuntu Bionic Universe as I did;

Find /usr/lib/python2.7/dist-packages/ansible/modules/cloud/misc/proxmox.py or wherever it ended up.

add 'import re' to the imports

and then change     
        VZ_TYPE = 'openvz' if float(proxmox.version.get()['version']) < 4.0 else
to
        pve_version = re.sub(r'-\d$', '', proxmox.version.get()['version'])
        VZ_TYPE = 3 if float(pve_version) < 4.0 else int(pve_version.split('.')[0])

copy/paste from morph27's solution, made it work on my system.

**Comment by UhtredTheBold** [comment]
I'm not seeing the same results with containers. I tried @GreatWhiteMuffloN's changes to proxmox.py and was getting `exception: getattr(): attribute name must be string"`

instead I changed the second line to
`VZ_TYPE = 'openvz' if float(pve_version) < 4.0 else 'lxc'` and it's now working.

I've not tested kvm

**Comment by morph027** [comment]
Ah, sure forgot about the containers...will implement this too.

**Comment by GreatWhiteMuffloN** [comment]
You are correct, the changes I posted only allowed for some commands to execute successfully, so it's faulty, and shouldn't be used.

**Comment by GreatWhiteMuffloN** [comment]
When it comes to the proxmox.py there is a version check in the pubkey component as well, line 351.
