### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by nzlosh** [swayf/proxmoxer#85]
What is the current status of this project?  Is it still being actively maintained?

There hasn't been a commit to master since September 2018 and there are 10 pull requests waiting since July 2018.

**Comment by morph027** [comment]
Same question ... looks like there is a community which is using and improving. Guess everybody would be more than happy to contribute and use in the future too.

I've setup an organization at https://github.com/proxmoxer/proxmoxer where we might end up as a team of maintainers. Just drop me a comment if you want to join.

Anyway, massive thanks to @swayf for creating this project! :tada: :+1: :cake:
