### ISSUE TITLE
proxmoxer/backends/https.py:78 fails on python3.4

### ISSUE THREAD

**Issue by kokuev** [swayf/proxmoxer#9]
Hi!
Here is code from proxmoxer/backends/https.py:78

            if isinstance(v, file):

The problem is that there is no 'file' class in python3.
There are some way to solve that problem:
1) use io.IOBase:

import io

         if isinstance(v, io.IOBase):

that will drop python < 2.6
2) use separate function for each python:
```
import sys

if sys.version_info[0] >= 3:
	import io
	def is_file(obj): return isinstance(obj, io.IOBase)
else: 
	def is_file(obj): return isinstance(obj, file)
```

Unfortunatly, I cannot upload patch to make pull requests, so I write it here.

**Comment by swayf** [comment]
nice catch :) thank you. (shame on me.. I did not use it with python3) I will repair it on the days.

**Comment by kokuev** [comment]
Thank you! It'll be nice, because I don't want to patch it manually on every host =)

My coworker wants to extend README with some examples. Should he put it here as issues, too?
Some queries are tricky and it's easier when you have working example.

**Comment by swayf** [comment]
Yea.. sure :) some more examples  is always good idea.

**Comment by swayf** [comment]
updated on pypi
